services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Jyz8myMouse
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  taskappeba:
    build:
      context: .
      dockerfile: TaskAppEBA/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sqlserver
    environment:
      - ConnectionStrings__DefaultConnection=Server=dockercompose9436897743579848051-sqlserver-1;Database=TaskDb;User Id=sa;Password=Jyz8myMouse;Encrypt=False;Trust Server Certificate=True;
    command: >
      /bin/sh -c "dotnet ef database update --no-build && dotnet your_app.dll"

volumes:
  sql_data:

